AdamsFirstMVC/Controllers/AlternateViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdamsFirstMVC.Controllers
{
    public class AlternateViewController : Controller
    {
        // GET: AlternateView
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Feature()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }
        public ActionResult Bands()
        {
            return View();
        }
        public ActionResult Event_Calendar()
        {
            return View();
        }
        public ActionResult Contact()
        {
            return View();
        }
    }
}

AdamsFirstMVC/Controllers/MandMController.cs
using System;
using System.Configuration;
using System.Net;
using AdamsFirstMVC.DAL;
using System.Web.Mvc;
using System.Net.Mail;
using System.Text;
using AdamsFirstMVC.Models;
using CaptchaMvc.HtmlHelpers;

namespace AdamsFirstMVC.Controllers
{
    public class MandMController : Controller
    {
        private readonly BandsUnitOfWork _bandsUnitOfWork;
        private readonly AboutUnitOfWork _aboutUnitOfWork;
        private readonly DJUnitOfWork _dJUnitOfWork;

        public MandMController()
        {
            _bandsUnitOfWork = new BandsUnitOfWork();
            _aboutUnitOfWork = new AboutUnitOfWork();
            _dJUnitOfWork = new DJUnitOfWork();
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View(_aboutUnitOfWork);
        }

        public ActionResult Bands()
        {
            return View(_bandsUnitOfWork);
        }
        public ActionResult DJs()
        {
            return View(_dJUnitOfWork);
        }

        public ActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Contact(Contact contact)
        {
            if (this.IsCaptchaValid("Validate your Captcha"))
                ViewBag.ErrMessage = "Validation Message";

            if (ModelState.IsValid)
            {
                try
                {
                    MailMessage msg = new MailMessage();
                    SmtpClient smtp = new SmtpClient();
                    StringBuilder sb = new StringBuilder();
                    MailAddress from = new MailAddress(ConfigurationManager.AppSettings["smtpFromAddress"]);

                    smtp.Host = ConfigurationManager.AppSettings["smtpHost"];
                    smtp.EnableSsl =  Convert.ToBoolean(ConfigurationManager.AppSettings["smtpSsl"]);
                    smtp.Port = Convert.ToInt16(ConfigurationManager.AppSettings["smtpPort"]);
                    smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                    smtp.Credentials = new NetworkCredential(ConfigurationManager.AppSettings["smtpEmail"],
                        ConfigurationManager.AppSettings["smtpPassword"]);

                    sb.Append("First name: " + contact.FirstName);
                    sb.Append(Environment.NewLine);
                    sb.Append("Last name: " + contact.LastName);
                    sb.Append(Environment.NewLine);
                    sb.Append("Email: " + contact.Email);
                    sb.Append(Environment.NewLine);
                    sb.Append("Comments: " + contact.Comment);

                    msg.To.Add(ConfigurationManager.AppSettings["smtpToAddresses"]);
                    msg.From = from;
                    msg.Subject = "Contact Us";
                    msg.IsBodyHtml = false;
                    msg.Body = sb.ToString();
                    smtp.Send(msg);
                    msg.Dispose();
                    return View("Success");
                }
                catch (Exception e)
                {
                    return View("Error");
                }
            }
            return View();
        }
    }
}

AdamsFirstMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Adam Rusch</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AdamRusch.net", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @* SET string for navbar, set controller view method and controller name (in that order)  *@
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Project", "Index", "MandM")</li>
                </ul>
                @* default call to view _LoginPartial *@
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Adam Rusch's ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AdamsFirstMVC/Views/Shared/_LayoutAlt.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Adam Rusch</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body id="BSO_background" class="img-responsive"> 
    <div class="navbar navbar-inverse navbar-fixed-top" id="navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("M&M Productions", "Index", "AlternateView", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @* SET string for navbar, set controller view method for view and controller name (in that order)  *@
                    <li>@Html.ActionLink("Feature", "Feature", "AlternateView")</liid="center-try">
                    <li>@Html.ActionLink("About", "About", "AlternateView")</li>
                    <li>@Html.ActionLink("Bands", "Bands", "AlternateView")</li>
                    <li>@Html.ActionLink("Event Calendar", "Event_Calendar", "AlternateView")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "AlternateView")</li>
                </ul>
                @* default call to view loginPartial *@
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @*<hr />*@
        @*<footer>
            <p>&copy; @DateTime.Now.Year - Adam Rusch's ASP.NET Application</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AdamsFirstMVC/Views/Shared/_LayoutMandMHome.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Adam Rusch</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/buttonRespond")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</head>
<body id="BSO_background" class="img-responsive">

@* FACEBOOK SCRIPT START *@
<div id="fb-root"></div>
<script>
    (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.9";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
@* FACEBOOK SCRIPT END *@

<div class="navbar navbar-inverse navbar-fixed-bottom" id="homepage-navbar-overrides">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse" id="center-align-nav-content">
            <ul class="nav navbar-nav" id="larger-button-center-helper">
                @* SET navbar route, view name and layout name (in that order)  *@
                <li><a href="@Url.Action("About", "MandM")" onmousedown="return mouseClicked('aboutButton')" onmouseup="return mouseUnclicked('aboutButton')"><img name="aboutButton" src="../../images/missionbeveledbutton.jpg" id="homepage-button-overrides" class="thumbnail img-responsive" alt="About"></a></li>
                <li><a href="@Url.Action("Bands", "MandM")" onmousedown="return mouseClicked('bandsButton')" onmouseup="return mouseUnclicked('bandsButton')"><img name="bandsButton" src="../../images/musicbeveledbutton.jpg" id="homepage-button-overrides" class="thumbnail img-responsive" alt="Bands"></a></li>
                <li><a href="@Url.Action("DJs", "MandM")" onmousedown="return mouseClicked('dJButton')" onmouseup="return mouseUnclicked('dJButton')"><img name="dJButton" src="../../images/djsbeveledbutton.jpg" id="homepage-button-overrides" class="thumbnail img-responsive" alt="DJs"></a></li>
                <li><a href="@Url.Action("Contact", "MandM")" onmousedown="return mouseClicked('contactButton')" onmouseup="return mouseUnclicked('contactButton')"><img name="contactButton" src="../../images/contactbeveledbutton.jpg" id="homepage-button-overrides" class="thumbnail img-responsive" alt="Contact"></a></li>
            </ul>
            <ul class="nav navbar-nav" id="smaller-content-helper">
                @* SET string for navbar, set controller view method and controller name (in that order)  *@
                <li>@Html.ActionLink("About", "About", "MandM")</li>
                <li>@Html.ActionLink("Bands", "Bands", "MandM")</li>
                <li>@Html.ActionLink("DJ's", "DJs", "MandM")</li>
                <li>@Html.ActionLink("Contact", "Contact", "MandM")</li>
            </ul>
            @* default call to view loginPartial *@
            @*@Html.Partial("_LoginPartial")*@
        </div>
    </div>
</div>
<div class="container body-content">
    @RenderBody()

    @*<hr />*@
    @*<footer>
                <p>&copy; @DateTime.Now.Year - Adam Rusch's ASP.NET Application</p>
            </footer>*@
</div>



</body>
</html>